apiVersion: 1

datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: postgres
    access: proxy
    url: postgres:5432
    user: medusa_user
    secureJsonData:
      password: $__env{GF_DB_PASSWORD}
    jsonData:
      database: medusa_hovedopgave
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true